apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/host

namespace: tenant2
namePrefix: dev-

patches:
  - target:
      kind: Cluster
    patch: |-
      - op: replace
        path: /spec/servers
        value: 1
      - op: replace
        path: /spec/agents
        value: 1
