---
# 1: Create the Rancher cluster representation in the management cluster (local)
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: k3k-automation-rancher
  namespace: fleet-local
spec:
  repo: "${GIT_REPO_URL}"
  branch: ${GIT_BRANCH}
  paths:
    - manifests/rancher
  targets:
    - clusterName: local

---
# 2: Deploy the k3k virtual cluster resource to the downstream host cluster
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: k3k-automation-host
  namespace: fleet-default
spec:
  repo: "${GIT_REPO_URL}"
  branch: ${GIT_BRANCH}
  paths:
    - manifests/host
  targets:
    - clusterName: ${HOST_CLUSTER_NAME}
