apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: dev-k3k-automation-host
  namespace: fleet-default
spec:
  branch: kustomize
  paths:
    - manifests/host
  repo: https://github.com/fultux/rancher-k3k-automation.git
  targets:
    - clusterName: kubevip
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: dev-k3k-automation-rancher
  namespace: fleet-local
spec:
  branch: kustomize
  paths:
    - manifests/rancher
  repo: https://github.com/fultux/rancher-k3k-automation.git
  targets:
    - clusterName: local
