apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: demo-shared
  namespace: fleet-default
  annotations:
    ui.rancher/k3k-namespace: tenant1
    ui.rancher/parent-cluster: c-m-7wmqrvqm
    ui.rancher/parent-cluster-display: host
    ui.rancher/provider: k3k
    rancher.io/imported-cluster-version-management: "false"
