apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: dev-cluster-base
  namespace: tenant2
spec:
  agents: 1
  mode: shared
  persistence:
    storageClassName: harvester
    storageRequestSize: 3Gi
    type: dynamic
  servers: 1
  version: v1.33.10-k3s1
