apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: k3k-fleet-test
  namespace: tenant2 # Must match the ui.rancher/k3k-namespace annotation in manifest-rancher
spec:
  mode: virtual
  k3sArgs:
    - --disable=traefik
    - --disable=servicelb
  version: v1.33.10-k3s1
  servers: 1
  agents: 1
  persistence:
    type: dynamic
    storageClassName: "harvester"
    storageRequestSize: 3Gi
