apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: k3k-fleet-test
  namespace: fleet-default
  labels:
    deploy-metallb: allowed
  annotations:
    ui.rancher/k3k-namespace: tenant2
    ui.rancher/parent-cluster: c-m-8jclnfjn
    ui.rancher/parent-cluster-display: kubevip
    ui.rancher/provider: k3k
    rancher.io/imported-cluster-version-management: "false"
spec: {}
