apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/rancher

namePrefix: dev-

patches:
  - target:
      kind: Cluster
    patch: |-
      - op: replace
        path: /metadata/annotations/ui.rancher~1k3k-namespace
        value: tenant2
